### ISSUE TITLE
能把警告处理掉就好了

### ISSUE THREAD

**Issue by WHYBBE** [JustDoIt0910/XMLParser#1]
哈哈又是我
这个纯C的项目就没啥问题了，裸指针爱咋用咋用
看了这个项目感觉你对C语言和数据结构的理解十分到位
警告无非是出在`malloc`,`strncpy`等和内存打交道的函数上
虽然一般使用不会出太多问题，`malloc`失败的话电脑也基本撑不住了，
但是基于严谨和鲁棒性的角度考虑还是得注意一下这些警告
最后，你代码写的真心还可以，挺想和你做项目的，如果有什么好的点子可以叫上我呀

**Comment by JustDoIt0910** [comment]
谢谢大佬呀。你现在也在读大学吗？

**Comment by WHYBBE** [comment]
> 谢谢大佬呀。你现在也在读大学吗？

大四了快毕业了，快成无业游民了

**Comment by JustDoIt0910** [comment]
你在上海上学吗

**Comment by WHYBBE** [comment]
> 你在上海上学吗

对啊，在上海海事大学，还挺羡慕你的学校的（如果是hdu的话）

**Comment by JustDoIt0910** [comment]
我是在杭电一个中外合作办学的学院

**Comment by JustDoIt0910** [comment]
因为疫情外教来不了，专业课全是网课哈哈哈

**Comment by WHYBBE** [comment]
> 因为疫情外教来不了，专业课全是网课哈哈哈

有什么关系呢，毕业工作基本只看学校名，
网课挺好的，安逸~
我大二的时候也正好疫情在家，不过我水了一个学期，老后悔了

**Comment by JustDoIt0910** [comment]
我感觉在家比在学校学得快哈哈
